version: '3'

services:
  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - .:/data
    depends_on:
      - db
   
  db:
    image: postgres
    container_name: db
  web:
    container_name: web
    build: ./docker/web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  celery:
    container_name: celery
    build: ./docker/web
    command: celery -A backend -l info worker
    volumes:
     - .:/code
    depends_on:
      - db
      - redis
  nginx:
    build: ./docker/nginx
    container_name: ng_server
    depends_on:
      - web
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"
    volumes:
      - ./static:/var/www/static
